version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: intelliquiz_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: intelliquiz
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql